### PR TITLE
fix no weapons in inventory

### PR DESCRIPTION
**Pull request by RoqueDEV**
This will fix the bug from that if you use /openinventory or you are using the police body search thing it will show the other player weapons in his inventory.

### CODE REVIEW

**Comment by dwiprizzy** [comment]
didnt work,

**Comment by DoluTattoo** [comment]
Thats cool but if I confiscate a weapon, the weapon have not bullet

**Comment by ItsTaras** [comment]
It's not work, i still cannot see weapons in the inventory.

**Comment by draZer0** [comment]
Thanks! It works!

**Pull request merged**
